# mybatis setting
mybatis:
  mapper-locations: xml/**/*.xml

spring:
  # DB setting
  datasource:
    url: jdbc:mariadb://localhost:3306/greengram_ver1
    username: root
    password: green502

  servlet:
    multipart:
      max-file-size: 10MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    operations-sorter: method
    path: /swagger
  cache:
    disabled: true