# custom property (절대경로 Absolute Path)
file:
  directory: D:/2024-02/download/greengram_ver1

default-page-size: 20

# mybatis setting
mybatis:
  mapper-locations: xml/**/*.xml

# Base URL setting
#server:
#  servlet:
#    context-path: /api

spring:
  # DB setting
  datasource:
    url: jdbc:mariadb://localhost:3306/greengram_ver1
    username: root
    password: green502

  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true
